version: 0.2
env:
  variables:
    REPOSITORY: https://github.com/iheanyi1989/vue
    REGION: us-east-1
    DOMAIN: info.diasporabro.com
    BRANCHNAME: feature/dev

phases:
  install:
    commands:
      - echo $CROSS_ACCOUNT_ROLE
      - echo $CF_EXECUTION_ROLE
      - echo $TARGET_ACCOUNT_ID
      - cd $CODEBUILD_SRC_DIR
      - chmod +x cross-account-setup.sh
  build:
    commands:
      - echo "Running CloudFormation Deploy.."
      - cd $CODEBUILD_SRC_DIR
      - . ./cross-account-setup.sh
      - >
        aws cloudformation deploy --template-file ./vuecfn.yml --stack-name testcodebuildvuecfn --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --parameter-overrides Domain=$DOMAIN Repository=$REPOSITORY BranchName=$BRANCHNAME
      - echo "Done."
artifacts:
  files:
    - packaged.yml
    - parameters/*.json
