AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Repository:
    Type: String
    Description: GitHub Repository URL

  # AccessToken:
  #   Type: String
  #   Description: GitHub Repository URL
  #   NoEcho: true

  Domain:
    Type: String
    Description: Domain name to host application

  BranchName:
    Type: String
    Description: The branch to build from

Resources:
  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      # Policies:
      #   - PolicyName: Amplify
      #     PolicyDocument:
      #       Version: 2012-10-17
      #       Statement:
      #         - Effect: Allow
      #           Action: "amplify:*"
      #           Resource: "*"

      Policies:
        - PolicyName: Justfortesting
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"

  AmplifyApp:
    Type: "AWS::Amplify::App"
    Properties:
      Name: TodoApp2
      Repository: !Ref Repository
      Description: Todo example app Test Pipeline
      # AccessToken: !Ref AccessToken
      AccessToken: "{{resolve:secretsmanager:vuecfncodepipeline}}"
      BuildSpec: |-
        version: 0.1
        # backend:
        #   phases:
        #     build:
        #       commands:
        #         - amplifyPush --simple
        frontend:
          phases:
            build:
              commands:
                - cp dist/vue.min.js examples/todomvc/
          artifacts:
            baseDirectory: examples/todomvc/
            files:
              - '*'
      CustomRules:
        - Source: /dist/vue.min.js
          Target: /vue.min.js
          Status: "200"
      Tags:
        - Key: Name
          Value: Todo
      IAMServiceRole: !GetAtt AmplifyRole.Arn

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: !Ref BranchName
      AppId: !GetAtt AmplifyApp.AppId
      Description: Amplify app testing
      EnableAutoBuild: true
      Tags:
        - Key: Name
          Value: todo-feature
        - Key: Branch
          Value: !Ref BranchName

  AmplifyDomain:
    Type: AWS::Amplify::Domain
    Properties:
      DomainName: !Ref Domain
      AppId: !GetAtt AmplifyApp.AppId
      SubDomainSettings:
        - Prefix: master
          BranchName: !GetAtt AmplifyBranch.BranchName

Outputs:
  DefaultDomain:
    Value: !GetAtt AmplifyApp.DefaultDomain

  MasterBranchUrl:
    Value:
      !Join [
        ".",
        [!GetAtt AmplifyBranch.BranchName, !GetAtt AmplifyDomain.DomainName],
      ]
